theme: jekyll-theme-minimal

title: Doodle
description: Minimalistic paint application for Android
logo: https://saifkhichi96.github.io/projects/apps/doodle/portfolio.png

show_downloads: false
google_analytics: 174802021
